### ISSUE TITLE
doesnt compile on macos 12.2

### ISSUE THREAD

**Issue by deus777** [espadrine/shishua-python#1]
creating build/temp.macosx-10.9-x86_64-3.9
  creating build/temp.macosx-10.9-x86_64-3.9/src
  creating build/temp.macosx-10.9-x86_64-3.9/src/binding
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/vic/opt/anaconda3/include -arch x86_64 -I/Users/vic/opt/anaconda3/include -fPIC -O2 -isystem /Users/vic/opt/anaconda3/include -arch x86_64 -Isrc/binding -I/Users/vic/opt/anaconda3/include/python3.9 -c src/binding/binding.c -o build/temp.macosx-10.9-x86_64-3.9/src/binding/binding.o -march=native -g
  In file included from src/binding/binding.c:715:
  src/binding/buffered-shishua.h:22:18: warning: incompatible pointer types passing 'buffered_shishua_state **' (aka 'struct buffered_shishua_state **') to parameter of type 'void **' [-Wincompatible-pointer-types]
    posix_memalign(&bss, 128, sizeof(buffered_shishua_state));
                   ^~~~
  /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mm_malloc.h:19:34: note: passing argument to parameter '__memptr' here
  extern int posix_memalign(void **__memptr, size_t __alignment, size_t __size);
                                   ^
  In file included from src/binding/binding.c:715:
  src/binding/buffered-shishua.h:74:36: error: integer literal is too large to be represented in any integer type
    return shishua_next_uint64(st) / 0x10000000000000000;
                                     ^
  src/binding/buffered-shishua.h:74:34: warning: division by zero is undefined [-Wdivision-by-zero]
    return shishua_next_uint64(st) / 0x10000000000000000;
                                   ^ ~~~~~~~~~~~~~~~~~~~
  2 warnings and 1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for shishua
Failed to build shishua
ERROR: Could not build wheels for shishua which use PEP 517 and cannot be installed directly

**Comment by deus777** [comment]
not sure how to fix this even I add ULL or LLU to the constant its still too large for the clang compiler on the mac.

the only way to get this to compile is to lop a 0 from the constant.  is there some special significance to the value?
